version: '3'

volumes:
  dynamodb_data:

services:
  get-all:
    build: .
    container_name: get-all
    env_file:
      - ./.env
    volumes:
      - ./get-all/:/var/task/src/
      - ./tmp/:/tmp/
    networks:
      - local-api-network
  dynamo-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamo-local
    hostname: dynamo-local
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    networks:
      - local-api-network
    volumes:
      - dynamodb_data:/home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
  test:
    image: amd64/ubuntu:latest
    env_file:
      - ./.env
    networks:
      - local-api-network
networks:
  local-api-network:
    driver: bridge